#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")

if env.get("pulseaudio") and env["use_sowrap"]:
    env.add_source_files(env.drivers_sources, "pulse-so_wrap.c")

env.add_source_files(env.drivers_sources, "*.cpp")
