#!/usr/bin/env python
from misc.utility.scons_hints import *

import test_builders

Import("env")

env_tests = env.Clone()
tests_sources = []

# We must disable the THREAD_LOCAL entirely in doctest to prevent crashes on debugging
# Since we link with /MT thread_local is always expired when the header is used
# So the debugger crashes the engine and it causes weird errors
# Explained in https://github.com/onqtam/doctest/issues/401
if env_tests["platform"] == "windows":
    env_tests.Append(CPPDEFINES=[("DOCTEST_THREAD_LOCAL", "")])

if env["disable_exceptions"]:
    env_tests.Append(CPPDEFINES=["DOCTEST_CONFIG_NO_EXCEPTIONS_BUT_WITH_ALL_ASSERTS"])

env_tests.add_source_files(tests_sources, "*.cpp")  # ["test_macros.cpp", "test_main.cpp", "test_utils.cpp"])
lib = env_tests.add_library("tests", tests_sources)
env.Prepend(LIBS=[lib])

env.Depends(
    lib, env.CommandNoCache("force_link.gen.h", "test_validate_testing.cpp", env.Run(test_builders.force_link_builder))
)

# # Link test objects directly.
# test_library_objects = []
# env_tests.add_source_files(test_library_objects, "test_validate_testing.cpp")
# # env_tests.add_source_files(test_library_objects, "core/**/*.cpp")
# # env_tests.add_source_files(test_library_objects, "scene/**/*.cpp")
# # env_tests.add_source_files(test_library_objects, "servers/**/*.cpp")

# env.Append(LIBS=test_library_objects)
