#!/usr/bin/env python
from misc.utility.scons_hints import *

import test_builders

Import("env")

env.force_link_obj = []

env.SConscript("core/SCsub")
env.SConscript("scene/SCsub")
env.SConscript("servers/SCsub")

# Sources with tests must be explicitly linked.
# NOTE: Passing the sources as a value, instead of an array of source files, as we only care about
#  regenerating if files are added/removed. A file being modified is irrelevant for this generator.
force_link_header = env.CommandNoCache(
    "force_link.gen.h", env.Value(env.force_link_obj), env.Run(test_builders.force_link_builder)
)
env.Depends(force_link_header, "test_builders.py")

tests_obj = []
env.add_source_files(tests_obj, "*.cpp")

lib = env.add_library("tests", tests_obj + env.force_link_obj)
env.Prepend(LIBS=[lib])
