#!/usr/bin/env python
from misc.utility.scons_hints import *

import glob

import test_builders

Import("env")

env_tests = env.Clone()

# We must disable the THREAD_LOCAL entirely in doctest to prevent crashes on debugging
# Since we link with /MT thread_local is always expired when the header is used
# So the debugger crashes the engine and it causes weird errors
# Explained in https://github.com/onqtam/doctest/issues/401
if env_tests["platform"] == "windows":
    env_tests.Append(CPPDEFINES=[("DOCTEST_THREAD_LOCAL", "")])

if env["disable_exceptions"]:
    env_tests.Append(CPPDEFINES=["DOCTEST_CONFIG_NO_EXCEPTIONS_BUT_WITH_ALL_ASSERTS"])

# Sources with tests; must be explicitly linked.
force_link_sources = []
env_tests.add_source_files(force_link_sources, "test_validate_testing.cpp")
env_tests.add_source_files(force_link_sources, glob.glob("core/**/*.cpp", recursive=True))
env_tests.add_source_files(force_link_sources, glob.glob("scene/**/*.cpp", recursive=True))
env_tests.add_source_files(force_link_sources, glob.glob("servers/**/*.cpp", recursive=True))

force_link_header = env.CommandNoCache(
    "force_link.gen.h", force_link_sources, env.Run(test_builders.force_link_builder)
)
env.Depends(force_link_header, "test_builders.py")

# Sources without tests; can be added like normal.
tests_sources = []
env_tests.add_source_files(tests_sources, ["test_macros.cpp", "test_main.cpp", "test_utils.cpp"])
lib = env_tests.add_library("tests", tests_sources + force_link_sources)
env.Prepend(LIBS=[lib])
