name: Upload Godot artifact
description: Upload the Godot artifact.

inputs:
  name:
    description: The artifact name.
    default: ${{ github.job }}
  path:
    description: The path to upload.
    required: true
    default: bin/*
  compression:
    description: The amount of compression to apply
    default: 6

runs:
  using: composite
  steps:
    - name: Upload Godot Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.name }}
        path: ${{ inputs.path }}
        compression-level: ${{ inputs.compression }}
        # Default is 90 days.
        retention-days: 7
