#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")

env.add_source_files(env.force_link_obj, "*.cpp")

if not env["disable_navigation_3d"]:
    env.SConscript("navigation/SCsub")
