name: 📊 Static Checks
on:
  workflow_call:
    outputs:
      changed-files:
        description: A list of changed files, pre-filtered for parsing by clangd-tidy.
        value: ${{ jobs.static-checks.outputs.changed-files }}
      sources-changed:
        description: Determines if any source files were changed.
        value: ${{ jobs.static-checks.outputs.sources-changed }}
  workflow_dispatch:

jobs:
  static-checks:
    name: Code style, file formatting, and docs
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    outputs:
      changed-files: ${{ steps.changed-files.outputs.CLANGD_ALL_CHANGED_FILES }}
      sources-changed: ${{ steps.changed-files.outputs.SOURCES_ANY_CHANGED }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          fetch-depth: 0 # Treeless clone. Slightly less performant than a shallow clone, but makes finding diffs instantaneous.
          filter: tree:0 # See: https://github.blog/open-source/git/get-up-to-speed-with-partial-clone-and-shallow-clone/

      # This needs to happen before Python and npm execution; it must happen before any extra files are written.
      - name: .gitignore checks (gitignore_check.sh)
        run: |
          bash ./misc/scripts/gitignore_check.sh

      - name: Get changed files (action)
        uses: ./.github/actions/changed-files

      - name: Get changed files
        id: changed-files
        shell: sh
        run: |
          echo "::group::Determine 'BASE_SHA'"
          if git cat-file -e ${{ github.event.before }} > /dev/null 2>&1; then
            BASE_SHA="${{ github.event.before }}"
          else
            echo "Could not determine previous SHA; falling back to 'HEAD~1'."
            BASE_SHA="HEAD~1"
          fi
          echo "$BASE_SHA"
          echo "BASE_SHA=$BASE_SHA" >> "$GITHUB_OUTPUT"
          echo "::endgroup::"

          BASE_SHA="HEAD~100"

          echo "::group::Determine 'SOURCES_ANY_CHANGED'"
          # Determines if build actions should occur after static checks are ran. Broadly speaking, these
          #  files changing would result in SCons rebuilding the engine, or are otherwise pertinent to the
          #  buildsystem itself.
          SOURCES_ALL_CHANGED_FILES=$(git diff --name-only -z $BASE_SHA HEAD -- \
            '.github/{actions/*,workflows}/*.yml' \
            '**/{SConstruct,SCsub,*.py}' \
            '**/*.{h,hpp,hh,hxx,c,cpp,cc,cxx,m,mm,inc,glsl}' \
            'core/extension/gdextension_interface.json' \
            'misc/extension_api_validation/**' \
            'modules/*/tests/**' \
            'modules/mono/**/*.{cs,csproj,sln,props,targets}' \
            'platform/android/java/{gradle*,**/*.{jar,java,kt,gradle}}' \
            'platform/web/{package{,-lock}.json,js/**/*.js}' \
            'tests/**' \
          )
          echo "$SOURCES_ALL_CHANGED_FILES"
          [ -z "$SOURCES_ALL_CHANGED_FILES" ] && SOURCES_ANY_CHANGED="false" || SOURCES_ANY_CHANGED="true"
          echo "$SOURCES_ANY_CHANGED"
          echo "SOURCES_ANY_CHANGED=$SOURCES_ANY_CHANGED" >> "$GITHUB_OUTPUT"
          echo "::endgroup::"

          echo "::group::Determine 'CLANGD_ALL_CHANGED_FILES'"
          # Determines which files are appropriate for running clangd-tidy checks on. This is a subset out
          #  of necessity, as we're only evaluating a Linux runner.
          CLANGD_ALL_CHANGED_FILES=$(git diff --name-only -z $BASE_SHA HEAD -- \
            **/*.{h,hpp,hxx,hh,c,cpp,cxx,cc} \
            :(exclude)**/thirdparty/** \
            :(exclude)**/*-so_wrap.{h,c} \
            :(exclude)drivers/{apple*,core*,d3d12,metal,wasapi,windows,winmidi,xaudio2}/** \
            :(exclude)editor/shader/shader_baker/shader_baker_export_plugin_platform_{d3d12,metal}.{h,cpp} \
            :(exclude)modules/camera/camera_{android,macos,win}.{h,cpp} \
            :(exclude)modules/openxr/extensions/platform/openxr_{android,metal}_extension.{h,cpp} \
            :(exclude)platform/{android,ios,macos,visionos,web,windows}/** \
            platform/{android,ios,macos,visionos,web,windows}/{api,export}/*.{h,hpp,hxx,hh,c,cpp,cxx,cc} \
          | tr '\0' ' ')
          echo "$CLANGD_ALL_CHANGED_FILES"
          echo "CLANGD_ALL_CHANGED_FILES=$CLANGD_ALL_CHANGED_FILES" >> "$GITHUB_OUTPUT"
          echo "::endgroup::"

      - name: Style checks via prek
        uses: j178/prek-action@v3.0.0
        with:
          extra-args: --from-ref ${{ steps.changed-files.outputs.BASE_SHA }}

      - name: Force fail
        run: exit 1
